# Generated by Django 4.2.5 on 2023-10-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referals", "0002_referenceprofile_first_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referenceprofile",
            name="first_purchase",
            field=models.CharField(
                choices=[
                    ("fulfilled", "Fulfilled"),
                    ("not_fulfilled", "Not Fulfilled"),
                ],
                default="Not Fulfilled",
                max_length=20,
            ),
        ),
    ]
