# Generated by Django 4.2.5 on 2023-10-31 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0050_alter_reviews_review_date"),
        ("referals", "0003_alter_referenceprofile_first_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referenceprofile",
            name="first_purchase",
            field=models.CharField(
                choices=[
                    ("fulfilled", "Fulfilled"),
                    ("not_fulfilled", "Not Fulfilled"),
                ],
                default="not_fulfilled",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="referenceprofile",
            name="recommended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ref_by",
                to="products.custom_user",
            ),
        ),
        migrations.AlterField(
            model_name="referenceprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.custom_user"
            ),
        ),
    ]
