# Generated by Django 4.2.5 on 2023-10-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_transaction_transaction_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
