# Generated by Django 4.2.5 on 2023-10-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0048_alter_category_offer_discount_percentage"),
        ("wallet", "0003_alter_transaction_transaction_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.custom_user"
            ),
        ),
    ]
