# Generated by Django 4.2.3 on 2023-11-14 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
