# Generated by Django 4.2.5 on 2023-09-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoffers",
            name="offer",
        ),
        migrations.AddField(
            model_name="productoffers",
            name="offers",
            field=models.ManyToManyField(to="products.offers"),
        ),
        migrations.AlterField(
            model_name="pc",
            name="ram",
            field=models.CharField(
                blank=True,
                choices=[("8", "8GB"), ("16", "16GB"), ("32", "32GB"), ("64", "64GB")],
                max_length=20,
                null=True,
            ),
        ),
    ]
