# Generated by Django 4.2.5 on 2023-09-27 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_reviews_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.offers",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="on_sale",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="ProductOffers",
        ),
    ]
