# Generated by Django 4.2.5 on 2023-09-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_offer_product_on_sale_delete_productoffers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="offer",
        ),
        migrations.AddField(
            model_name="product",
            name="offers",
            field=models.ManyToManyField(blank=True, to="products.offers"),
        ),
    ]
