# Generated by Django 4.2.5 on 2023-09-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_offer_product_offers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="offers",
        ),
        migrations.AddField(
            model_name="product",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.offers",
            ),
        ),
    ]
