# Generated by Django 4.2.5 on 2023-09-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0008_address_phone_number_custom_user_alter_address_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="custom_user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Blocked", "Blocked")],
                default="Active",
                max_length=20,
                null=True,
            ),
        ),
    ]
