# Generated by Django 4.2.5 on 2023-10-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_subcategory_category_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="products.category",
            ),
        ),
    ]
