# Generated by Django 4.2.5 on 2023-10-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="main_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
            ),
        ),
    ]
