# Generated by Django 4.2.5 on 2023-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_product_subcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="main_category",
        ),
        migrations.AddField(
            model_name="product",
            name="subcategories",
            field=models.ManyToManyField(
                blank=True, null=True, to="products.subcategory"
            ),
        ),
    ]
