# Generated by Django 4.2.5 on 2023-10-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_remove_product_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="subcategories",
            field=models.ManyToManyField(blank=True, to="products.subcategory"),
        ),
    ]
