# Generated by Django 4.2.5 on 2023-10-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_subcategory_category_alter_product_subcategories"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
