# Generated by Django 4.2.5 on 2023-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_headphone_remove_keyboard_keyboard_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
