# Generated by Django 4.2.5 on 2023-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_product_product_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimages",
            name="image_url",
        ),
        migrations.AddField(
            model_name="productimages",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product/"
            ),
        ),
    ]
