# Generated by Django 4.2.5 on 2023-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0020_remove_productimages_image_url_productimages_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="headphone",
            name="headphone_type",
            field=models.CharField(
                blank=True,
                choices=[("Wired", "Wired"), ("Bluetooth", "Bluetooth")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="display_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("18", "18 inch"),
                    ("20", "20 inch"),
                    ("22", "22 inch"),
                    ("24", "24 inch"),
                    ("26", "26 inch"),
                    ("28", "28 inch"),
                    ("30", "30 inch"),
                    ("32", "32 inch"),
                    ("34", "34 inch"),
                    ("36", "36 inch"),
                    ("38", "38 inch"),
                    ("40", "40 inch"),
                    ("42", "42 inch"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="rating",
            field=models.IntegerField(
                choices=[(1, "⭐"), (2, "⭐⭐"), (3, "⭐⭐⭐"), (4, "⭐⭐⭐⭐"), (5, "⭐⭐⭐⭐⭐")],
                default=1,
            ),
        ),
    ]
