# Generated by Django 4.2.5 on 2023-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_alter_headphone_headphone_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom_user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/users/"),
        ),
    ]
