# Generated by Django 4.2.5 on 2023-10-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_product_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
