# Generated by Django 4.2.5 on 2023-10-17 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_orderitems_user_alter_orderitems_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="price_per_product",
        ),
    ]
