# Generated by Django 4.2.5 on 2023-10-17 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0029_remove_orderitems_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.orders",
            ),
            preserve_default=False,
        ),
    ]
