# Generated by Django 4.2.5 on 2023-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_orderitems_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
    ]
