# Generated by Django 4.2.5 on 2023-10-18 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_orderitems_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="price",
        ),
    ]
