# Generated by Django 4.2.5 on 2023-10-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_orderitems_selling_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
    ]
