# Generated by Django 4.2.5 on 2023-10-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_return_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="return",
            name="user",
        ),
        migrations.AlterField(
            model_name="return",
            name="status",
            field=models.CharField(
                choices=[("Confirmed", "Confirmed"), ("Pending", "Pending")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
