# Generated by Django 4.2.5 on 2023-10-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0038_alter_address_user_alter_orderitems_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="is_returned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="return",
            name="status",
            field=models.CharField(
                choices=[("Confirmed", "Confirmed"), ("Pending", "Pending")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
