# Generated by Django 4.2.5 on 2023-10-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0040_alter_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(
                choices=[
                    ("Processing", "Processing"),
                    ("Confirmed", "Confirmed"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Processing",
                max_length=20,
            ),
        ),
    ]
