# Generated by Django 4.2.5 on 2023-10-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0044_alter_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
