# Generated by Django 4.2.5 on 2023-10-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0046_category_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_offer",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/category/"
            ),
        ),
        migrations.AlterField(
            model_name="return",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
