# Generated by Django 4.2.5 on 2023-10-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0047_category_offer_banner_alter_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category_offer",
            name="discount_percentage",
            field=models.IntegerField(),
        ),
    ]
