# Generated by Django 4.2.5 on 2023-10-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0048_alter_category_offer_discount_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="return",
            name="status",
            field=models.CharField(
                choices=[("Confirmed", "Confirmed"), ("Pending", "Pending")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
