# Generated by Django 4.2.5 on 2023-10-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0049_alter_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_date",
            field=models.DateField(auto_now=True),
        ),
    ]
