# Generated by Django 4.2.3 on 2023-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0052_alter_return_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_variant",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="return",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Confirmed", "Confirmed")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
