# Generated by Django 4.2.3 on 2023-11-15 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0059_alter_orders_order_date_alter_return_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="order_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 15, 15, 1, 42, 699430, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
